trust_level_flair_position:
  default: "bottom-left"
  type: enum
  choices:
    - "bottom-right"
    - "top-right"
    - "top-left"
    - "overlap"
group_flair_always_on_top:
  default: true
  type: bool
  description: "For positions where the trust flair overlaps, or is in the same position as group flair."
use_font_awesome:
  default: false
  type: bool
  description: "<span>This will enable font awesome to be used in the flair image fields below. Use the name of the icon 
    like <b>heart</b> or <b>plane</b>. <a href='https://fontawesome.com/v4.7.0/icons/' target='_blank'>Click Here</a> 
    to view the list of availible icons."
font_awsome_color:
  default: "#ffffff"
  type: string
font_awsome_background_color:
  default: "#000000"
  type: string
new_user_flair_image:
  default: ""
  type: string
  description: "The image URL for the new user trust level (TL0).
    TIP: Use the inlcuded template image to create your own image. Upload your image to this theme,
    then right-click on the link to your upload, copy the image address, and then paste the link
    into this textbox."
basic_user_flair_image:
  default: ""
  type: string
  description: "The image URL for the basic user trust level (TL1).
    TIP: Use the inlcuded template image to create your own image. Upload your image to this theme,
    then right-click on the link to your upload, copy the image address, and then paste the link
    into this textbox."
member_flair_image:
  default: ""
  type: string
  description: "The image URL for the member trust level (TL2).
    TIP: Use the inlcuded template image to create your own image. Upload your image to this theme,
    then right-click on the link to your upload, copy the image address, and then paste the link
    into this textbox."
regular_flair_image:
  default: ""
  type: string
  description: "The image URL for the regular trust level (TL3).
    TIP: Use the inlcuded template image to create your own image. Upload your image to this theme,
    then right-click on the link to your upload, copy the image address, and then paste the link
    into this textbox."
leader_flair_image:
  default: ""
  type: string
  description: "The image URL for the leader trust level (TL4).
    TIP: Use the inlcuded template image to create your own image. Upload your image to this theme,
    then right-click on the link to your upload, copy the image address, and then paste the link
    into this textbox."
